### ISSUE TITLE
writeText() won't work without document being focused

### ISSUE THREAD

**Issue by guest271314** [mkazemiraz/one-line-javascript-utility-codes#3]
[const copyToClipboard = (text) => navigator.clipboard.writeText(text);](https://github.com/mkazemiraz/one-line-javascript-utility-codes#copy-text-to-clipboard)

**Comment by mkazemiraz** [comment]
Thank you for bringing up the issue with the copy-to-clipboard code. I kindly request you create a Pull Request and address the problem by making the necessary code modifications. This will allow you to contribute to the project by resolving the issue. It also provides you with an opportunity to share your expertise and skills with the repository. We look forward to seeing your contribution.

**Comment by guest271314** [comment]
I'm not sure if the code to achieve the requirement can be written in one line.
